apiVersion: scone/5.8
kind: genservice

# define environment variables
#  - local ones are kept confidential, i.e., only visible to this service
#  - global ones are defined for all services in a mesh

environment:
  local: # export env vars to other services
    - name: SCONE_HEAP
      value: 760M
    - name: SCONE_LOG
      value: error
    - name: API_PASSWORD
      value: "$$SCONE::password$$"  # get from CAS
  global:     # import env vars from other services. Their values are set in the meshfile
    - name: API_USER  # get value from Meshfile

# define secrets that are managed by CAS 
secrets:
  global: 
  - name: password
    kind: ascii
    size: 10

build:
  name: python-hello-user
  kind: python
  to: registry.scontain.com:5050/cicd/tutorial_windows/goodimagename:latest
  pwd: /python
  command: python3 print_env.py
  copy:
    - print_env.py
  run:
    - > 
     echo "You can also RUN additional commands in the same way as docker build RUN commands"
     && echo "If you use multi-line commands, please do not forget to start lines with &&."
     && echo "A multi-line command like this will be added as a single line. No need for \\"
    - echo "Or use single line command"
    - echo "Each command is executed by a single RUN command"
